version: '2'
#todos los microservicios
services:
  #microservicio de contactenos
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: users-db
      MYSQL_USER: sa
      MYSQL_PASSWORD: 123
    ports:
      - "3308:3308"
  web:
    container_name: web
    image: dieosiris23/user-ms
    command: bash -c "sleep 10 && rake db:drop db:create db:migrate db:seed && bundle exec rails s -p 3001 -b '0.0.0.0'"
    ports:
      - "3001:3001"
  #microservicio de lists
  lists-db:
     image: postgres
     environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lists-db
     ports:
       - "5432:5432"
  lists-ms:
    container_name: lists-ms
    image: dieosiris23/lists-ms
    environment:
      PORT: '4004'
    command: bash -c "sleep 40 && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:4004"
    depends_on:
      - lists-db
  activities-ms:
    container_name: activities-ms
    image: dieosiris23/activity-ms
    environment:
      PORT: '4000'
    depends_on:
      - activities-db
  #base de datos de contactenos
  activities-db:
    container_name: activities-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: activities-db
      MYSQL_USER: sa
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3307"
  places-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: places-db
      MYSQL_USER: sa
      MYSQL_PASSWORD: 123
    ports:
      - "3309:3309"
  places-ms:
    container_name: places-ms
    image: dieosiris23/places-ms
    ports:
      - "5000:5000"
    links:
      - places-db:sql_srv
    depends_on:
      - places-db 
  trails-ms:
    container_name: trails-ms
    image: dieosiris23/trails-ms
    environment:
      PORT: '3002'
    tty: true
    depends_on:
    - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
  #Inteface SOAP
  senderos-un-soap:
    container_name: senderos-un-soap
    image: dieosiris23/senderos_un-soap
    command: bash -c "rails s -p 3005 -b '0.0.0.0'"
    environment:
      PORT: '3005'
  senderosun-wa:
    container_name: senderosun-wa
    image: dieosiris23/senderosun_wa
    ports:
      - "3000:3000"
  #api gateway para graphql
  mafenix-api:
    container_name: mafenix-api
    image: dieosiris23/api_getway
    environment:
      PORT: '5500'
      SHOW_URLS: 'true'
      LISTS_URL: 'lists-ms'
      LISTS_PORT: '4004'
      LISTS_ENTRY: 'lists-ms'
      ACTIVITIES_URL: 'activities-ms'
      ACTIVITIES_PORT: '4000'
      ACTIVITIES_ENTRY: 'activities-ms/resources/activities'
      SCORERESOURCES_URL: 'places-ms'
      SCORERESOURCES_PORT: '5000'
      SCORERESOURCES_ENTRY: 'scoreservice'
      USERS_URL: 'web'
      USERS_PORT: '3001'
      USERS_BY_EMAIL_ENTRY: 'users_by_email'
      USERS_ENTRY: 'users'
      USERS_SIGNUP_ENTRY: 'signup'
      USERS_LOGIN_ENTRY: 'login'
      USERS_VERIFY_JWT: 'verify_token'
      TRAILS_URL: 'trails-ms'
      TRAILS_PORT: '3002'
      TRAILS_ENTRY: 'trails-ms'
      INTERFACE_URL: 'senderos_un-soap'
      INTERFACE_PORT: '3005'
      INTERFACE_ENTRY: 'connect_gropu_c'
  # Proxy
  senderos-proxy:
    container_name: senderos-proxy
    image: dieosiris23/senderos-proxy
    ports:
      - "80:80"
  # LDAP 
  senderos-ldap:
    image: osixia/openldap:1.1.8
    environment:
      COMPOSE_HTTP_TIMEOUT: 200
      PORT: '389'
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Software Architecture - Group D"
      LDAP_DOMAIN: "senderosun.unal.edu.co"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      #LDAP_READONLY_USER_USERNAME: "readonly"
      #LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_BACKEND: "hdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      #LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn="cn=admin,cn=config" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_DB_SYNCPROV: "binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    hostname: "senderosun.org"
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "senderos-ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8085:80"
    links:
      - senderos-ldap