version: '3'
#todos los microservicios
services:
  #microservicio de contactenos
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5434:5432"
    volumes:
      - /var/lib/postgresql/data
  web:
    container_name: web
    image: dieosiris23/user-ms
    environment:
      PORT: '3001'
    command: bash -c "sleep 40 && rake db:drop db:create db:migrate db:seed && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/user-ms
    depends_on:
      - db
  #microservicio de lists
  lists-db:
     image: postgres
     environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lists-db
     ports:
       - "5432:5432"
  lists-ms:
    container_name: lists-ms
    image: dieosiris23/lists-ms
    environment:
      PORT: '4004'
    command: bash -c "sleep 40 && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:4004"
    depends_on:
      - lists-db
  activities-ms:
    container_name: activities-ms
    image: dieosiris23/activity-ms
    environment:
      PORT: '4000'
    depends_on:
      - activities-db
  #base de datos de contactenos
  activities-db:
    container_name: activities-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: activities-db
      MYSQL_USER: sa
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3307"
  scoreresources-ms:
    container_name: scoreresources-ms
    image: dieosiris23/scoreresources-ms
    environment:
      PORT: '5000'
    depends_on:
      - scoreresources-db
  #base de datos de calificaciones
  scoreresources-db:
    container_name: scoreresources-db
    image: mongo
    ports:
      - "27018:27018"
  trails-ms:
    container_name: trails-ms
    image: dieosiris23/trails-ms
    environment:
      PORT: '3002'
    tty: true
    depends_on:
    - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  #api gateway para graphql
  mafenix-api:
    container_name: mafenix-api
    image: dieosiris23/api_getway
    environment:
      PORT: '5500'
      SHOW_URLS: 'true'
      LISTS_URL: 'lists-ms'
      LISTS_PORT: '4004'
      LISTS_ENTRY: 'lists-ms'
      ACTIVITIES_URL: 'activities-ms'
      ACTIVITIES_PORT: '4000'
      ACTIVITIES_ENTRY: 'activities-ms/resources/activities'
      SCORERESOURCES_URL: 'scoreresources-ms'
      SCORERESOURCES_PORT: '5000'
      SCORERESOURCES_ENTRY: 'scoreservice'
      USERS_URL: 'web'
      USERS_PORT: '3001'
      USERS_BY_EMAIL_ENTRY: 'users_by_email'
      USERS_ENTRY: 'users'
      USERS_SIGNUP_ENTRY: 'signup'
      USERS_LOGIN_ENTRY: 'login'
      USERS_VERIFY_JWT: 'verify_token'
      TRAILS_URL: 'trails-ms'
      TRAILS_PORT: '3002'
      TRAILS_ENTRY: 'trails-ms'
  senderos-proxy:
    container_name: senderos-proxy
    image: dieosiris23/senderos-proxy
    ports:
      - "80:80"
  senderos_un-soap:
    container_name: senderos_un-soap
    image: dieosiris23/senderos_un-soap
    command: bash -c "rails s -p 3005 -b '0.0.0.0'"
    environment:
      PORT: '3005'
